-- begin SPEEDYPIZZA_ORDER
alter table SPEEDYPIZZA_ORDER add constraint FK_SPEEDYPIZZA_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SPEEDYPIZZA_CUSTOMER(ID)^
alter table SPEEDYPIZZA_ORDER add constraint FK_SPEEDYPIZZA_ORDER_ON_EMPLOYER foreign key (EMPLOYER_ID) references SPEEDYPIZZA_EMPLOYER(ID)^
create index IDX_SPEEDYPIZZA_ORDER_ON_CUSTOMER on SPEEDYPIZZA_ORDER (CUSTOMER_ID)^
create index IDX_SPEEDYPIZZA_ORDER_ON_EMPLOYER on SPEEDYPIZZA_ORDER (EMPLOYER_ID)^
-- end SPEEDYPIZZA_ORDER
-- begin SPEEDYPIZZA_CUSTOMER
alter table SPEEDYPIZZA_CUSTOMER add constraint FK_SPEEDYPIZZA_CUSTOMER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SPEEDYPIZZA_CUSTOMER_ON_USER on SPEEDYPIZZA_CUSTOMER (USER_ID)^
-- end SPEEDYPIZZA_CUSTOMER
-- begin SPEEDYPIZZA_DISH
alter table SPEEDYPIZZA_DISH add constraint FK_SPEEDYPIZZA_DISH_ON_ORDER foreign key (ORDER_ID) references SPEEDYPIZZA_ORDER(ID)^
create index IDX_SPEEDYPIZZA_DISH_ON_ORDER on SPEEDYPIZZA_DISH (ORDER_ID)^
-- end SPEEDYPIZZA_DISH
-- begin SPEEDYPIZZA_DELIVERY
alter table SPEEDYPIZZA_DELIVERY add constraint FK_SPEEDYPIZZA_DELIVERY_ON_EMPLOYER foreign key (EMPLOYER_ID) references SPEEDYPIZZA_EMPLOYER(ID)^
alter table SPEEDYPIZZA_DELIVERY add constraint FK_SPEEDYPIZZA_DELIVERY_ON_ORDER foreign key (ORDER_ID) references SPEEDYPIZZA_ORDER(ID)^
create index IDX_SPEEDYPIZZA_DELIVERY_ON_EMPLOYER on SPEEDYPIZZA_DELIVERY (EMPLOYER_ID)^
create index IDX_SPEEDYPIZZA_DELIVERY_ON_ORDER on SPEEDYPIZZA_DELIVERY (ORDER_ID)^
-- end SPEEDYPIZZA_DELIVERY
-- begin SPEEDYPIZZA_EMPLOYER
alter table SPEEDYPIZZA_EMPLOYER add constraint FK_SPEEDYPIZZA_EMPLOYER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SPEEDYPIZZA_EMPLOYER_ON_USER on SPEEDYPIZZA_EMPLOYER (USER_ID)^
-- end SPEEDYPIZZA_EMPLOYER
-- begin SPEEDYPIZZA_DISH_PRODUCTS_LINK
alter table SPEEDYPIZZA_DISH_PRODUCTS_LINK add constraint FK_DISPRO_ON_PRODUCTS foreign key (PRODUCTS_ID) references SPEEDYPIZZA_PRODUCTS(ID)^
alter table SPEEDYPIZZA_DISH_PRODUCTS_LINK add constraint FK_DISPRO_ON_DISH foreign key (DISH_ID) references SPEEDYPIZZA_DISH(ID)^
-- end SPEEDYPIZZA_DISH_PRODUCTS_LINK
